In [1]:
import sys
from utils.path import get_git_root
sys.path.insert(0, get_git_root().as_posix())

from utils.api_client import APIClient
from scripts.config import API_PUB_BASE_URL, RT_PACKAGE_PARAMS

client = APIClient(API_PUB_BASE_URL, RT_PACKAGE_PARAMS)
client.get_endpoints()

{'system regions': 'https://tor.publicbikesystem.net/ube/gbfs/v1/en/system_regions',
 'system_information': 'https://tor.publicbikesystem.net/ube/gbfs/v1/en/system_information',
 'station_information': 'https://tor.publicbikesystem.net/ube/gbfs/v1/en/station_information',
 'station_status': 'https://tor.publicbikesystem.net/ube/gbfs/v1/en/station_status',
 'system_pricing_plans': 'https://tor.publicbikesystem.net/ube/gbfs/v1/en/system_pricing_plans'}

In [2]:
station_endpoint = client.fetch_data("station_information")
station_endpoint["last_updated"]

1782322770

In [3]:
station_info = station_endpoint["data"]["stations"]
station_info[:2]

[{'station_id': '7000',
  'external_id': 'f8aa7900-e9c7-11ef-984e-124c66246c7d',
  'name': 'Fort York  Blvd / Capreol Ct',
  'physical_configuration': 'REGULAR',
  'lat': 43.639832,
  'lon': -79.395954,
  'altitude': None,
  'address': 'Fort York  Blvd / Capreol Ct',
  'capacity': 47,
  'is_charging_station': False,
  'rental_methods': ['key', 'transitcard', 'creditcard', 'phone'],
  'groups': ['South', 'Fort York - Entertainment District'],
  'obcn': '647-643-9607',
  'short_name': '647-643-9607',
  'nearby_distance': 500.0,
  '_ride_code_support': True,
  'rental_uris': {}},
 {'station_id': '7002',
  'external_id': 'f8aaef03-e9c7-11ef-984e-124c66246c7d',
  'name': 'St. George St / Bloor St W',
  'physical_configuration': 'REGULAR',
  'lat': 43.66713121831853,
  'lon': -79.3995550638237,
  'altitude': None,
  'address': 'St. George St / Bloor St W',
  'capacity': 19,
  'is_charging_station': False,
  'rental_methods': ['key', 'transitcard', 'creditcard', 'phone'],
  'groups': ['South', 'U of T - Hospital Row'],
  'obcn': '647-643-9615',
  'short_name': '647-643-9615',
  'nearby_distance': 500.0,
  '_ride_code_support': True,
  'rental_uris': {}}]

In [4]:
import pandas as pd

df = pd.DataFrame(station_info)
df.head()

,station_id,external_id,name,physical_configuration,lat,lon,altitude,address,capacity,is_charging_station,...,groups,obcn,short_name,nearby_distance,_ride_code_support,rental_uris,is_valet_station,post_code,cross_street,_valet_station_details
0,7000,f8aa7900-e9c7-11ef-984e-124c66246c7d,Fort York Blvd / Capreol Ct,REGULAR,43.639832,-79.395954,NaN,Fort York Blvd / Capreol Ct,47,False,...,"[South, Fort York - Entertainment District]",647-643-9607,647-643-9607,500.0,True,{},NaN,NaN,NaN,NaN
1,7002,f8aaef03-e9c7-11ef-984e-124c66246c7d,St. George St / Bloor St W,REGULAR,43.667131,-79.399555,NaN,St. George St / Bloor St W,19,False,...,"[South, U of T - Hospital Row]",647-643-9615,647-643-9615,500.0,True,{},NaN,NaN,NaN,NaN
2,7003,f8ab20ac-e9c7-11ef-984e-124c66246c7d,Madison Ave / Bloor St W,REGULAR,43.667018,-79.402796,NaN,Madison Ave / Bloor St W,15,False,...,"[South, Bloor St W / Annex]",647-631-4587,647-631-4587,500.0,True,{},NaN,NaN,NaN,NaN
3,7005,f8ab51f8-e9c7-11ef-984e-124c66246c7d,King St W / York St,VAULT,43.648001,-79.383177,0.0,King St W / York St,23,False,...,"[South, Financial District]",647-643-9693,647-643-9693,500.0,True,{},NaN,NaN,NaN,NaN
4,7006,f8ab54c0-e9c7-11ef-984e-124c66246c7d,Bay St / College St (East Side),REGULAR,43.660439,-79.385525,NaN,Bay St / College St (East Side),31,False,...,"[South, U of T - Hospital Row]",416-569-2349,416-569-2349,500.0,True,{},False,NaN,NaN,NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1047 entries, 0 to 1046
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   station_id              1047 non-null   object
 1   external_id             1047 non-null   object
 2   name                    1047 non-null   object
 3   physical_configuration  1044 non-null   object
 4   lat                     1047 non-null   float64
 5   lon                     1047 non-null   float64
 6   altitude                662 non-null    float64
 7   address                 1046 non-null   object
 8   capacity                1047 non-null   int64
 9   is_charging_station     1047 non-null   bool
 10  rental_methods          1044 non-null   object
 11  groups                  1047 non-null   object
 12  obcn                    1047 non-null   object
 13  short_name              1047 non-null   object
 14  nearby_distance         1047 non-null   float64
 15  _ride_code_support      1047 non-null   bool
 16  rental_uris             1047 non-null   object
 17  is_valet_station        40 non-null     object
 18  post_code               756 non-null    object
 19  cross_street            382 non-null    object
 20  _valet_station_details  1 non-null      object
dtypes: bool(2), float64(4), int64(1), object(14)
memory usage: 157.6+ KB

In [6]:
df["altitude"].unique()

array([   nan,   0.  ,   1.  , 102.08])

In [7]:
df["is_valet_station"].unique()

array([nan, False, True], dtype=object)

In [8]:
df["nearby_distance"].nunique()

35

In [9]:
# drop altitude, groups, obc, rental_uris, _ride_code_support, cross_street, is_valet_station
cleaned = df.drop(columns=["altitude", "groups", "obcn", "rental_uris", "_ride_code_support", "cross_street", "is_valet_station"])
cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1047 entries, 0 to 1046
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   station_id              1047 non-null   object
 1   external_id             1047 non-null   object
 2   name                    1047 non-null   object
 3   physical_configuration  1044 non-null   object
 4   lat                     1047 non-null   float64
 5   lon                     1047 non-null   float64
 6   address                 1046 non-null   object
 7   capacity                1047 non-null   int64
 8   is_charging_station     1047 non-null   bool
 9   rental_methods          1044 non-null   object
 10  short_name              1047 non-null   object
 11  nearby_distance         1047 non-null   float64
 12  post_code               756 non-null    object
 13  _valet_station_details  1 non-null      object
dtypes: bool(1), float64(3), int64(1), object(9)
memory usage: 107.5+ KB

In [10]:
cleaned["physical_configuration"].unique()

array(['REGULAR', 'VAULT', 'SMARTMAPFRAME', 'ELECTRICBIKESTATION', nan],
      dtype=object)

In [11]:
cleaned[cleaned["physical_configuration"].isna()]

,station_id,external_id,name,physical_configuration,lat,lon,address,capacity,is_charging_station,rental_methods,short_name,nearby_distance,post_code,_valet_station_details
642,7794,f8c983a7-e9c7-11ef-984e-124c66246c7d,York St / Harbour St (Love Park),NaN,43.641017,-79.380359,York St / Harbour St (Love Park),16,False,NaN,96 Queens Quay W,350.0,M5J,NaN
955,8147,581b99ab-da3e-11f0-b51f-1214620ec1db,Widmer St / Adelaide St W (South),NaN,43.647300,-79.391313,Widmer St / Adelaide St W (South),8,False,NaN,Widmer St / Adelaide St W,20.0,M5V 2E8,NaN
956,8148,581b9c51-da3e-11f0-b51f-1214620ec1db,Simcoe St / Wellington St W (North) 2,NaN,43.646246,-79.385489,Simcoe St / Wellington St W,4,False,NaN,Simcoe St / Wellington St W,10.0,M5J 0C2,NaN

In [12]:
cleaned[cleaned["address"].isna()]

,station_id,external_id,name,physical_configuration,lat,lon,address,capacity,is_charging_station,rental_methods,short_name,nearby_distance,post_code,_valet_station_details
688,7844,f8ca3017-e9c7-11ef-984e-124c66246c7d,Second St / Lake Shore Blvd W,VAULT,43.601915,-79.499419,NaN,15,False,"[key, transitcard, phone]",Ward 3 - (2765 Lake Shore Blvd W),350.0,M8V 1H2,NaN

In [13]:
cleaned[cleaned["name"] == cleaned["address"]].shape[0]

654

In [14]:
#set all nulls to the station name
cleaned["address"].fillna(cleaned["name"], inplace=True)

/var/folders/kx/0yxjmr611n9b7fnqf983rl700000gn/T/ipykernel_56464/2573472537.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cleaned["address"].fillna(cleaned["name"], inplace=True)

In [15]:
cleaned[cleaned["name"] == cleaned["address"]].shape[0]

655

In [16]:
#replace missing config, rental methods, and postal code with "UNKNOWN"
df.columns[df.isnull().any()].tolist()

['physical_configuration',
 'altitude',
 'address',
 'rental_methods',
 'is_valet_station',
 'post_code',
 'cross_street',
 '_valet_station_details']

In [17]:
#cast dtype

In [18]:
import geopandas as gpd
import folium

gdf = gpd.GeoDataFrame(
    df,
    geometry=gpd.points_from_xy(df.lon, df.lat),
    crs="EPSG:4326"
)

map = folium.Map(location=[43.67, -79.38], zoom_start=13)

folium.GeoJson(
    gdf,
    name="Stations",
    popup=folium.GeoJsonPopup(
        fields=["name", "address", "capacity"],
        aliases=["Station Name:", "Address:", "Capacity:"]
    ),
    tooltip=folium.GeoJsonTooltip(fields=["name"], aliases=[""])
).add_to(map)

map

In [19]:
map._repr_html_()

'<div style="width:100%;"><div style="position:relative;width:100%;height:0;padding-bottom:60%;"><span style="color:#565656">Make this Notebook Trusted to load map: File -> Trust Notebook</span><iframe srcdoc="&lt;!DOCTYPE html&gt;\n&lt;html&gt;\n&lt;head&gt;\n    \n    &lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;\n    &lt;script src=&quot;https://cdn.jsdelivr.net/npm/leaflet@1.9.3/dist/leaflet.js&quot;&gt;&lt;/script&gt;\n    &lt;script src=&quot;https://code.jquery.com/jquery-3.7.1.min.js&quot;&gt;&lt;/script&gt;\n    &lt;script src=&quot;https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js&quot;&gt;&lt;/script&gt;\n    &lt;script src=&quot;https://cdnjs.cloudflare.com/ajax/libs/Leaflet.awesome-markers/2.0.2/leaflet.awesome-markers.js&quot;&gt;&lt;/script&gt;\n    &lt;link rel=&quot;stylesheet&quot; href=&quot;https://cdn.jsdelivr.net/npm/leaflet@1.9.3/dist/leaflet.css&quot;/&gt;\n    &lt;link rel=&quot;stylesheet&quot; href=&quot;https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css&quot;/&gt;\n    &lt;link rel=&quot;stylesheet&quot; href=&quot;https://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css&quot;/&gt;\n    &lt;link rel=&quot;stylesheet&quot; href=&quot;https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.2.0/css/all.min.css&quot;/&gt;\n    &lt;link rel=&quot;stylesheet&quot; href=&quot;https://cdnjs.cloudflare.com/ajax/libs/Leaflet.awesome-markers/2.0.2/leaflet.awesome-markers.css&quot;/&gt;\n    &lt;link rel=&quot;stylesheet&quot; href=&quot;https://cdn.jsdelivr.net/gh/python-visualization/folium/folium/templates/leaflet.awesome.rotate.min.css&quot;/&gt;\n    \n            &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width,\n                initial-scale=1.0, maximum-scale=1.0, user-scalable=no&quot; /&gt;\n            &lt;style&gt;\n                #map_d1d155a0abda49eb12488bdea5af18f8 {\n                    position: relative;\n                    width: 100.0%;\n                    height: 100.0%;\n                    left: 0.0%;\n                    top: 0.0%;\n                }\n                .leaflet-container { font-size: 1rem; }\n            &lt;/style&gt;\n\n            &lt;style&gt;html, body {\n                width: 100%;\n                height: 100%;\n                margin: 0;\n                padding: 0;\n            }\n            &lt;/style&gt;\n\n            &lt;style&gt;#map {\n                position:absolute;\n                top:0;\n                bottom:0;\n                right:0;\n                left:0;\n                }\n            &lt;/style&gt;\n\n            &lt;script&gt;\n                L_NO_TOUCH = false;\n                L_DISABLE_3D = false;\n            &lt;/script&gt;\n\n        \n    \n                    &lt;style&gt;\n                        .foliumtooltip {\n                            \n                        }\n                       .foliumtooltip table{\n                            margin: auto;\n                        }\n                        .foliumtooltip tr{\n                            text-align: left;\n                        }\n                        .foliumtooltip th{\n                            padding: 2px; padding-right: 8px;\n                        }\n                    &lt;/style&gt;\n            \n    \n                    &lt;style&gt;\n                        .foliumpopup {\n                            margin: auto;\n                        }\n                       .foliumpopup table{\n                            margin: auto;\n                        }\n                        .foliumpopup tr{\n                            text-align: left;\n                        }\n                        .foliumpopup th{\n                            padding: 2px; padding-right: 8px;\n                        }\n                    &lt;/style&gt;\n            \n&lt;/head&gt;\n&lt;body&gt;\n    \n    \n            &lt;div class=&quot;folium-map&quot; id=&quot;map_d1d155a0abda49eb12488bdea5af18f8&quot; &gt;&lt;/div&gt;\n        \n&lt;/body&gt;\n&lt;script&gt;\n    \n    \n            var map_d1d155a0abda49eb12488bdea5af18f8 = L.map(\n                &quot;map_d1d155a0abda49eb12488bdea5af18f8&quot;,\n                {\n                    center: [43.67, -79.38],\n                    crs: L.CRS.EPSG3857,\n                    ...{\n  &quot;zoom&quot;: 13,\n  &quot;zoomControl&quot;: true,\n  &quot;preferCanvas&quot;: false,\n}\n\n                }\n            );\n\n            \n\n        \n    \n            var tile_layer_b11d984f4e1eb685db9caa4c4341acc5 = L.tileLayer(\n                &quot;https://tile.openstreetmap.org/{z}/{x}/{y}.png&quot;,\n                {\n  &quot;minZoom&quot;: 0,\n  &quot;maxZoom&quot;: 19,\n  &quot;maxNativeZoom&quot;: 19,\n  &quot;noWrap&quot;: false,\n  &quot;attribution&quot;: &quot;\\u0026copy; \\u003ca href=\\&quot;https://www.openstreetmap.org/copyright\\&quot;\\u003eOpenStreetMap\\u003c/a\\u003e contributors&quot;,\n  &quot;subdomains&quot;: &quot;abc&quot;,\n  &quot;detectRetina&quot;: false,\n  &quot;tms&quot;: false,\n  &quot;opacity&quot;: 1,\n}\n\n            );\n        \n    \n            tile_layer_b11d984f4e1eb685db9caa4c4341acc5.addTo(map_d1d155a0abda49eb12488bdea5af18f8);\n        \n    \n\n        function geo_json_cf3c518b87d7ff6d678108a1ad8c91b5_onEachFeature(feature, layer) {\n\n            layer.on({\n            });\n        };\n        var geo_json_cf3c518b87d7ff6d678108a1ad8c91b5 = L.geoJson(null, {\n                onEachFeature: geo_json_cf3c518b87d7ff6d678108a1ad8c91b5_onEachFeature,\n            \n            ...{\n}\n        });\n\n        function geo_json_cf3c518b87d7ff6d678108a1ad8c91b5_add (data) {\n            geo_json_cf3c518b87d7ff6d678108a1ad8c91b5\n                .addData(data);\n        }\n            geo_json_cf3c518b87d7ff6d678108a1ad8c91b5_add({&quot;bbox&quot;: [-79.60346425086402, 43.5880774, -79.1231844760227, 43.812642480301804], &quot;features&quot;: [{&quot;bbox&quot;: [-79.395954, 43.639832, -79.395954, 43.639832], &quot;geometry&quot;: {&quot;coordinates&quot;: [-79.395954, 43.639832], &quot;type&quot;: &quot;Point&quot;}, &quot;id&quot;: &quot;0&quot;, &quot;properties&quot;: {&quot;_ride_code_support&quot;: true, &quot;_valet_station_details&quot;: null, &quot;address&quot;: &quot;Fort York  Blvd / Capreol Ct&quot;, &quot;altitude&quot;: null, &quot;capacity&quot;: 47, &quot;cross_street&quot;: null, &quot;external_id&quot;: &quot;f8aa7900-e9c7-11ef-984e-124c66246c7d&quot;, &quot;groups&quot;: [&quot;South&quot;, &quot;Fort York - Entertainment District&quot;], &quot;is_charging_station&quot;: false, &quot;is_valet_station&quot;: null, &quot;lat&quot;: 43.639832, &quot;lon&quot;: -79.395954, &quot;name&quot;: &quot;Fort York  Blvd / Capreol Ct&quot;, &quot;nearby_distance&quot;: 500.0, &quot;obcn&quot;: &quot;647-643-9607&quot;, &quot;physical_configuration&quot;: &quot;REGULAR&quot;, &quot;post_code&quot;: null, &quot;rental_methods&quot;: [&quot;key&quot;, &quot;transitcard&quot;, &quot;creditcard&quot;, &quot;phone&quot;], &quot;rental_uris&quot;: {}, &quot;short_name&quot;: &quot;647-643-9607&quot;, &quot;station_id&quot;: &quot;7000&quot;}, &quot;type&quot;: &quot;Feature&quot;}, {&quot;bbox&quot;: [-79.3995550638237, 43.66713121831853, -79.3995550638237, 43.66713121831853], &quot;geometry&quot;: {&quot;coordinates&quot;: [-79.3995550638237, 43.66713121831853], &quot;type&quot;: &quot;Point&quot;}, &quot;id&quot;: &quot;1&quot;, &quot;properties&quot;: {&quot;_ride_code_support&quot;: true, &quot;_valet_station_details&quot;: null, &quot;address&quot;: &quot;St. George St / Bloor St W&quot;, &quot;altitude&quot;: null, &quot;capacity&quot;: 19, &quot;cross_street&quot;: null, &quot;external_id&quot;: &quot;f8aaef03-e9c7-11ef-984e-124c66246c7d&quot;, &quot;groups&quot;: [&quot;South&quot;, &quot;U of T - Hospital Row&quot;], &quot;is_charging_station&quot;: false, &quot;is_valet_station&quot;: null, &quot;lat&quot;: 43.66713121831853, &quot;lon&quot;: -79.3995550638237, &quot;name&quot;: &quot;St. George St / Bloor St W&quot;, &quot;nearby_distance&quot;: 500.0, &quot;obcn&quot;: &quot;647-643-9615&quot;, &quot;physical_configuration&quot;: &quot;REGULAR&quot;, &quot;post_code&quot;: null, &quot;rental_methods&quot;: [&quot;key&quot;, &quot;transitcard&quot;, &quot;creditcard&quot;, &quot;phone&quot;], &quot;rental_uris&quot;: {}, &quot;short_name&quot;: &quot;647-643-9615&quot;, &quot;station_id&quot;: &quot;7002&quot;}, &quot;type&quot;: &quot;Feature&quot;}, {&quot;bbox&quot;: [-79.4027958687172, 43.66701830465472, -79.4027958687172, 43.66701830465472], &quot;geometry&quot;: {&quot;coordinates&quot;: [-79.4027958687172, 43.66701830465472], &quot;type&quot;: &quot;Point&quot;}, &quot;id&quot;: &quot;2&quot;, &quot;properties&quot;: {&quot;_ride_code_support&quot;: true, &quot;_valet_station_details&quot;: null, &quot;address&quot;: &quot;Madison Ave / Bloor St W&quot;, &quot;altitude&quot;: null, &quot;capacity&quot;: 15, &quot;cross_street&quot;: null, &quot;external_id&quot;: &quot;f8ab20ac-e9c7-11ef-984e-124c66246c7d&quot;, &quot;groups&quot;: [&quot;South&quot;, &quot;Bloor St W / Annex&quot;], &quot;is_charging_station&quot;: false, &quot;is_valet_station&quot;: null, &quot;lat&quot;: 43.66701830465472, &quot;lon&quot;: -79.4027958687172, &quot;name&quot;: &quot;Madison Ave / Bloor St W&quot;, &quot;nearby_distance&quot;: 500.0, &quot;obcn&quot;: &quot;647-631-4587&quot;, &quot;physical_configuration&quot;: &quot;REGULAR&quot;, &quot;post_code&quot;: null, &quot;rental_methods&quot;: [&quot;key&quot;, &quot;transitcard&quot;, &quot;creditcard&quot;, &quot;phone&quot;], &quot;rental_uris&quot;: {}, &quot;short_name&quot;: &quot;647-631-4587&quot;, &quot;station_id&quot;: &quot;7003&quot;}, &quot;type&quot;: &quot;Feature&quot;}, {&quot;bbox&quot;: [-79.383177, 43.6480008, -79.383177, 43.6480008], &quot;geometry&quot;: {&quot;coordinates&quot;: [-79.383177, 43.6480008], &quot;type&quot;: &quot;Point&quot;}, &quot;id&quot;: &quot;3&quot;, &quot;properties&quot;: {&quot;_ride_code_support&quot;: true, &quot;_valet_station_details&quot;: null, &quot;address&quot;: &quot;King St W / York St&quot;, &quot;altitude&quot;: 0.0, &quot;capacity&quot;: 23, &quot;cross_street&quot;: null, &quot;external_id&quot;: &quot;f8ab51f8-e9c7-11ef-984e-124c66246c7d&quot;, &quot;groups&quot;: [&quot;South&quot;, &quot;Financial District&quot;], &quot;is_charging_station&quot;: false, &quot;is_valet_station&quot;: null, &quot;lat&quot;: 43.6480008, &quot;lon&quot;: -79.383177, &quot;name&quot;: &quot;King St W / York St&quot;, &quot;nearby_distance&quot;: 500.0, &quot;obcn&quot;: &quot;647-643-9693&quot;, &quot;physical_configuration&quot;: &quot;VAULT&quot;, &quot;post_code&quot;: null, &quot;rental_methods&quot;: [&quot;key&quot;, &quot;transitcard&quot;, &quot;phone&quot;], &quot;rental_uris&quot;: {}, &quot;short_name&quot;: &quot;647-643-9693&quot;, &quot;station_id&quot;: &quot;7005&quot;}, &quot;type&quot;: &quot;Feature&quot;}, {&quot;bbox&quot;: [-79.385525, 43.660439, -79.385525, 43.660439], &quot;geometry&quot;: {&quot;coordinates&quot;: [-79.385525, 43.660439], &quot;type&quot;: &quot;Point&quot;}, &quot;id&quot;: &quot;4&quot;, &quot;properties&quot;: {&quot;_ride_code_support&quot;: true, &quot;_valet_station_details&quot;: null, &quot;address&quot;: &quot;Bay St / College St (East Side)&quot;, &quot;altitude&quot;: null, &quot;capacity&quot;: 31, &quot;cross_street&quot;: null, &quot;external_id&quot;: &quot;f8ab54c0-e9c7-11ef-984e-124c66246c7d&quot;, &quot;groups&quot;: [&quot;South&quot;, &quot;U of T - Hospital Row&quot;], &quot;is_charging_station&quot;: false, &quot;is_valet_station&quot;: false, &quot;lat&quot;: 43.660439, &quot;lon&quot;: -79.385525, &quot;name&quot;: &quot;Bay St / College St (East Side)&quot;, &quot;nearby_distance&quot;: 500.0, &quot;obcn&quot;: &quot;416-569-2349&quot;, &quot;physical_configuration&quot;: &quot;REGULAR&quot;, &quot;post_code&quot;: null, &quot;rental_methods&quot;: [&quot;key&quot;, &quot;transitcard&quot;, &quot;creditcard&quot;, &quot;phone&quot;], &quot;rental_uris&quot;: {}, &quot;short_name&quot;: &quot;416-569-2349&quot;, &quot;station_id&quot;: &quot;7006&quot;}, &quot;type&quot;: &quot;Feature&quot;}, {&quot;bbox&quot;: [-79.398167, 43.658148, -79.398167, 43.658148], &quot;geometry&quot;: {&quot;coordinates&quot;: [-79.398167, 43.658148], &quot;type&quot;: &quot;Point&quot;}, &quot;id&quot;: &quot;5&quot;, &quot;properties&quot;: {&quot;_ride_code_support&quot;: true, &quot;_valet_station_details&quot;: null, &quot;address&quot;: &quot;College St / Huron St&quot;, &quot;altitude&quot;: null, &quot;capacity&quot;: 19, &quot;cross_street&quot;: null, &quot;external_id&quot;: &quot;f8ab576d-e9c7-11ef-984e-124c66246c7d&quot;, &quot;groups&quot;: [&quot;South&quot;, &quot;U of T - Hospital Row&quot;], &quot;is_charging_station&quot;: false, &quot;is_valet_station&quot;: null, &quot;lat&quot;: 43.658148, &quot;lon&quot;: -79.398167, &quot;name&quot;: &quot;College St / Huron St&quot;, &quot;nearby_distance&quot;: 500.0, &quot;obcn&quot;: &quot;647-625-3582&quot;, &quot;physical_configuration&quot;: &quot;REGULAR&quot;, &quot;post_code&quot;: null, &quot;rental_methods&quot;: [&quot;key&quot;, &quot;transitcard&quot;, &quot;creditcard&quot;, &quot;phone&quot;], &quot;rental_uris&quot;: {}, &quot;short_name&quot;: &quot;647-625-3582&quot;, &quot;station_id&quot;: &quot;7007&quot;}, &quot;type&quot;: &quot;Feature&quot;}, {&quot;bbox&quot;: [-79.392125, 43.663376, -79.392125, 43.663376], &quot;geometry&quot;: {&quot;coordinates&quot;: [-79.392125, 43.663376], &quot;type&quot;: &quot;Point&quot;}, &quot;id&quot;: &quot;6&quot;, &quot;properties&quot;: {&quot;_ride_code_support&quot;: true, &quot;_valet_station_details&quot;: null, &quot;address&quot;: &quot;Wellesley St W / Queen\\u0027s Park Cres&quot;, &quot;altitude&quot;: null, &quot;capacity&quot;: 19, &quot;cross_street&quot;: null, &quot;external_id&quot;: &quot;f8ab5a3f-e9c7-11ef-984e-124c66246c7d&quot;, &quot;groups&quot;: [&quot;South&quot;, &quot;U of T - Hospital Row&quot;], &quot;is_charging_station&quot;: false, &quot;is_valet_station&quot;: null, &quot;lat&quot;: 43.663376, &quot;lon&quot;: -79.392125, &quot;name&quot;: &quot;Wellesley St W / Queen\\u0027s Park Cres&quot;, &quot;nearby_distance&quot;: 500.0, &quot;obcn&quot;: &quot;647-643-9648&quot;, &quot;physical_configuration&quot;: &quot;REGULAR&quot;, &quot;post_code&quot;: null, &quot;rental_methods&quot;: [&quot;key&quot;, &quot;transitcard&quot;, &quot;creditcard&quot;, &quot;phone&quot;], &quot;rental_uris&quot;: {}, &quot;short_name&quot;: &quot;647-643-9648&quot;, &quot;station_id&quot;: &quot;7008&quot;}, &quot;type&quot;: &quot;Feature&quot;}, {&quot;bbox&quot;: [-79.39510358283808, 43.64514249449372, -79.39510358283808, 43.64514249449372], &quot;geometry&quot;: {&quot;coordinates&quot;: [-79.39510358283808, 43.64514249449372], &quot;type&quot;: &quot;Point&quot;}, &quot;id&quot;: &quot;7&quot;, &quot;properties&quot;: {&quot;_ride_code_support&quot;: true, &quot;_valet_station_details&quot;: null, &quot;address&quot;: &quot;King St W / Spadina Ave&quot;, &quot;altitude&quot;: null, &quot;capacity&quot;: 19, &quot;cross_street&quot;: null, &quot;external_id&quot;: &quot;f8ab5fcc-e9c7-11ef-984e-124c66246c7d&quot;, &quot;groups&quot;: [&quot;South&quot;, &quot;Fort York - Entertainment District&quot;], &quot;is_charging_station&quot;: false, &quot;is_valet_station&quot;: null, &quot;lat&quot;: 43.64514249449372, &quot;lon&quot;: -79.39510358283808, &quot;name&quot;: &quot;King St W / Spadina Ave&quot;, &quot;nearby_distance&quot;: 500.0, &quot;obcn&quot;: &quot;647-202-6537&quot;, &quot;physical_configuration&quot;: &quot;REGULAR&quot;, &quot;post_code&quot;: null, &quot;rental_methods&quot;: [&quot;key&quot;, &quot;transitcard&quot;, &quot;creditcard&quot;, &quot;phone&quot;], &quot;rental_uris&quot;: {}, &quot;short_name&quot;: &quot;647-202-6537&quot;, &quot;station_id&quot;: &quot;7010&quot;}, &quot;type&quot;: &quot;Feature&quot;}, {&quot;bbox&quot;: [-79.37530913867988, 43.64659663170443, -79.37530913867988, 43.64659663170443], &quot;geometry&quot;: {&quot;coordinates&quot;: [-79.37530913867988, 43.64659663170443], &quot;type&quot;: &quot;Point&quot;}, &quot;id&quot;: &quot;8&quot;, &quot;properties&quot;: {&quot;_ride_code_support&quot;: true, &quot;_valet_station_details&quot;: null, &quot;address&quot;: &quot;Scott St / The Esplanade&quot;, &quot;altitude&quot;: 0.0, &quot;capacity&quot;: 19, &quot;cross_street&quot;: null, &quot;external_id&quot;: &quot;f8ab675c-e9c7-11ef-984e-124c66246c7d&quot;, &quot;groups&quot;: [&quot;South&quot;, &quot;Financial District&quot;], &quot;is_charging_station&quot;: false, &quot;is_valet_station&quot;: null, &quot;lat&quot;: 43.64659663170443, &quot;lon&quot;: -79.37530913867988, &quot;name&quot;: &quot;Scott St / The Esplanade&quot;, &quot;nearby_distance&quot;: 500.0, &quot;obcn&quot;: &quot;416-666-6440&quot;, &quot;physical_configuration&quot;: &quot;REGULAR&quot;, &quot;post_code&quot;: &quot;M5E 1Z4&quot;, &quot;rental_methods&quot;: [&quot;key&quot;, &quot;transitcard&quot;, &quot;creditcard&quot;, &quot;phone&quot;], &quot;rental_uris&quot;: {}, &quot;short_name&quot;: &quot;416-666-6440&quot;, &quot;station_id&quot;: &quot;7013&quot;}, &quot;type&quot;: &quot;Feature&quot;}, {&quot;bbox&quot;: [-79.373181, 43.663102, -79.373181, 43.663102], &quot;geometry&quot;: {&quot;coordinates&quot;: [-79.373181, 43.663102], &quot;type&quot;: &quot;Point&quot;}, &quot;id&quot;: &quot;9&quot;, &quot;properties&quot;: {&quot;_ride_code_support&quot;: true, &quot;_valet_station_details&quot;: null, &quot;address&quot;: &quot;Sherbourne St / Carlton St (Allan Gardens)&quot;, &quot;altitude&quot;: null, &quot;capacity&quot;: 17, &quot;cross_street&quot;: null, &quot;external_id&quot;: &quot;f8ab69cf-e9c7-11ef-984e-124c66246c7d&quot;, &quot;groups&quot;: [&quot;East&quot;, &quot;Church Wellesley / Yorkville&quot;], &quot;is_charging_station&quot;: false, &quot;is_valet_station&quot;: null, &quot;lat&quot;: 43.663102, &quot;lon&quot;: -79.373181, &quot;name&quot;: &quot;Sherbourne St / Carlton St (Allan Gardens)&quot;, &quot;nearby_distance&quot;: 500.0, &quot;obcn&quot;: &quot;416-710-6764&quot;, &quot;physical_configuration&quot;: &quot;REGULAR&quot;, &quot;post_code&quot;: null, &quot;rental_methods&quot;: [&quot;key&quot;, &quot;transitcard&quot;, &quot;creditcard&quot;, &quot;phone&quot;], &quot;rental_uris&quot;: {}, &quot;short_name&quot;: &quot;416-710-6764&quot;, &quot;station_id&quot;: &quot;7014&quot;}, &quot;type&quot;: &quot;Feature&quot;}, {&quot;bbox&quot;: [-79.380576, 43.64852, -79.380576, 43.64852], &quot;geometry&quot;: {&quot;coordinates&quot;: [-79.380576, 43.64852], &quot;type&quot;: &quot;Point&quot;}, &quot;id&quot;: &quot;10&quot;, &quot;properties&quot;: {&quot;_ride_code_support&quot;: true, &quot;_valet_station_details&quot;: null, &quot;address&quot;: &quot;King St W / Bay St (West Side)&quot;, &quot;altitude&quot;: null, &quot;capacity&quot;: 39, &quot;cross_street&quot;: null, &quot;external_id&quot;: &quot;f8ab6c2a-e9c7-11ef-984e-124c66246c7d&quot;, &quot;groups&quot;: [&quot;Valet Stations&quot;, &quot;South&quot;, &quot;Financial District&quot;], &quot;is_charging_station&quot;: false, &quot;is_valet_station&quot;: false, &quot;lat&quot;: 43.64852, &quot;lon&quot;: -79.380576, &quot;name&quot;: &quot;King St W / Bay St (West Side)&quot;, &quot;nearby_distance&quot;: 500.0, &quot;obcn&quot;: &quot;416-671-7595&quot;, &quot;physical_configuration&quot;: &quot;REGULAR&quot;, &quot;post_code&quot;: null, &quot;rental_methods&quot;: [&quot;key&quot;, &quot;transitcard&quot;, &quot;creditcard&quot;, &quot;phone&quot;], &quot;rental_uris&quot;: {}, &quot;short_name&quot;: &quot;416-671-7595&qu

In [20]:
station_status = client.fetch_data("station_status")
station_status["last_updated"]

1782322787

In [21]:
status_df = pd.DataFrame(station_status["data"]["stations"])
status_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1047 entries, 0 to 1046
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   station_id                 1047 non-null   object
 1   num_bikes_available        1047 non-null   int64
 2   num_bikes_disabled         1047 non-null   int64
 3   is_charging_station        1047 non-null   bool
 4   status                     1047 non-null   object
 5   traffic                    0 non-null      object
 6   num_bikes_available_types  1047 non-null   object
 7   num_docks_available        1047 non-null   int64
 8   num_docks_disabled         1047 non-null   int64
 9   last_reported              1047 non-null   int64
 10  is_installed               1047 non-null   int64
 11  is_renting                 1047 non-null   int64
 12  is_returning               1047 non-null   int64
dtypes: bool(1), int64(8), object(4)
memory usage: 99.3+ KB

In [22]:
status_df.head()

,station_id,num_bikes_available,num_bikes_disabled,is_charging_station,status,traffic,num_bikes_available_types,num_docks_available,num_docks_disabled,last_reported,is_installed,is_renting,is_returning
0,7000,2,1,False,IN_SERVICE,None,"{'mechanical': 2, 'ebike': 0}",44,0,1782322748,1,1,1
1,7002,2,1,False,IN_SERVICE,None,"{'mechanical': 2, 'ebike': 0}",15,1,1782322678,1,1,1
2,7003,0,0,False,IN_SERVICE,None,"{'mechanical': 0, 'ebike': 0}",15,0,1782322704,1,1,1
3,7005,21,2,False,IN_SERVICE,None,"{'mechanical': 21, 'ebike': 0}",0,0,1782322723,1,1,1
4,7006,18,1,False,IN_SERVICE,None,"{'mechanical': 18, 'ebike': 0}",9,3,1782322714,1,1,1

In [23]:
status_df["is_installed"].unique()

array([1])

In [24]:
status_df["is_renting"].unique()

array([1])

In [25]:
status_df["is_returning"].unique()

array([1])

In [26]:
status_df["is_charging_station"].unique()

array([False,  True])